### ISSUE TITLE
Multi module project support

### ISSUE THREAD

**Issue by holgerstolzenberg** [boxheed/gradle-sweeney-plugin#8]
I could not manage to set up Sweeney for a multi module project. If only applying to sub-module, rules cannot be parsed. If applying the plugin to top level `build.gradle`, the build runs without errors but ignored the enforced rules.

**Comment by boxheed** [comment]
Hi Holger, thanks for this I haven't tried this in a multi module project, I'll have a look. So that we are both on the same page could you post examples of the build scripts you are trying to apply.

**Comment by holgerstolzenberg** [comment]
You can checkout current MASTER of https://github.com/ewerk/gradle-plugins and try to enforce JDK-7 for the auto-value-plugin for example. Please use the new plugin definition syntax.

**Comment by boxheed** [comment]
Thanks will have a look

**Comment by holgerstolzenberg** [comment]
Great. Any schedule on this? I´d really like not to use an awkward task definition for that.

**Comment by boxheed** [comment]
I'm in the UK, so it's my afternoon now, I'll be able to concentrate on it this evening but will take a first look before then.

**Comment by boxheed** [comment]
Hi Holger, it looks like the plugin doesn't work when loaded using the plugin definition syntax, if you use the older syntax of buildscript dependencies then it should work, even within the multiproject build. I played around with putting it in the subprojects as well as the base project, but had the same results.

I simplified it to the following build script which doesn't work:

```
plugins {
  id "com.fizzpod.sweeney" version "1.0.0"
}

sweeney {
	enforce 'jdk:[1.8,)'
}
``` 

which results in `Unable to parse rule: jdk:[1.8,)`

However by using the the buildscript dependencies it does work.

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        // sweeney dependency
        classpath 'com.fizzpod:gradle-sweeney-plugin:1+'
    }
}

apply plugin: 'com.fizzpod.sweeney'

sweeney {
	enforce 'jdk:[1.8,)'
}
```

Which results in `Version 1.7.0 is not within specification: [expect:[1.8,), value:1.7.0_55, type:range, decription:JDK version rule]. Expression: (lowerVersion.isBelow(version) && upperVersion.isAbove(version))` which is what I would expect as my JDK is 1.7 and the requirement is a minimum version of 1.8

I suspect the way that the RuleDefinitionParsers are loaded (as well as the Rules themselves is not compatible for some reason with the Java Service Loader used to discover the rules and parsers. I will look for a solution to this.

**Comment by boxheed** [comment]
Hi Holger, I have created version 1.0.1 of the plugin which I think should work around the issue until I figure out what the root cause is. The current problem is that I rely on bintray syncing to the gradle plugin portal so that the plugins are available using the plugin syntax, however there appears to be a problem with the plugin syncing at the moment (http://discuss.gradle.org/t/plugins-deployed-to-bintray-not-syncing-to-the-portal-anymore/9227) and version 1.0.1 is not available in the portal; not sure when that is going to be resolved so I have not been able to test the changes.

Can you try using the old build script mechanism to confirm that that is behaving as you expect.

**Comment by holgerstolzenberg** [comment]
The process of deploying to Gradle portal has changed. See https://plugins.gradle.org/docs/submit. You will have to reclaim the plugin from Bintray and adopt your publishing process. That´s what I am doing right now with my plugins.

**Comment by boxheed** [comment]
No problem, hopefully the change works, I'll let you know when I get the plugin published, I've now reclaimed it so hopefully won't take long.

**Comment by boxheed** [comment]
Version 1.0.1 is now available in the plugin portal can you try it and let Mr know if it works.

**Comment by holgerstolzenberg** [comment]
Version 1.0.1 is working perfectly. Three lines of code and JDK-7 is enforced for the whole project. Thanks a lot for your very quick response and action.

**Comment by boxheed** [comment]
No problem, glad you find it useful.
